#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: CoreUObject

#include "Basic.hpp"


namespace SDK
{

// Enum CoreUObject.EInterpCurveMode
// NumValues: 0x0007
enum class EInterpCurveMode : uint8
{
	CIM_Linear                               = 0,
	CIM_CurveAuto                            = 1,
	CIM_Constant                             = 2,
	CIM_CurveUser                            = 3,
	CIM_CurveBreak                           = 4,
	CIM_CurveAutoClamped                     = 5,
	CIM_MAX                                  = 6,
};

// Enum CoreUObject.ERangeBoundTypes
// NumValues: 0x0004
enum class ERangeBoundTypes : uint8
{
	Exclusive                                = 0,
	Inclusive                                = 1,
	Open                                     = 2,
	ERangeBoundTypes_MAX                     = 3,
};

// Enum CoreUObject.ELocalizedTextSourceCategory
// NumValues: 0x0004
enum class ELocalizedTextSourceCategory : uint8
{
	Game                                     = 0,
	Engine                                   = 1,
	Editor                                   = 2,
	ELocalizedTextSourceCategory_MAX         = 3,
};

// Enum CoreUObject.EAutomationEventType
// NumValues: 0x0004
enum class EAutomationEventType : uint8
{
	Info                                     = 0,
	Warning                                  = 1,
	Error                                    = 2,
	EAutomationEventType_MAX                 = 3,
};

// Enum CoreUObject.EMouseCursor
// NumValues: 0x001A
enum class EMouseCursor : uint8
{
	None                                     = 0,
	Default                                  = 1,
	TextEditBeam                             = 2,
	ResizeLeftRight                          = 3,
	ResizeUpDown                             = 4,
	ResizeSouthEast                          = 5,
	ResizeSouthWest                          = 6,
	CardinalCross                            = 7,
	Crosshairs                               = 8,
	Hand                                     = 9,
	GrabHand                                 = 10,
	GrabHandClosed                           = 11,
	SlashedCircle                            = 12,
	EyeDropper                               = 13,
	Menu                                     = 14,
	Custom1                                  = 15,
	Custom2                                  = 16,
	Custom3                                  = 17,
	Custom4                                  = 18,
	Custom5                                  = 19,
	Custom6                                  = 20,
	Custom7                                  = 21,
	Custom8                                  = 22,
	Custom9                                  = 23,
	Custom10                                 = 24,
	EMouseCursor_MAX                         = 25,
};

// Enum CoreUObject.EPixelFormat
// NumValues: 0x0050
enum class EPixelFormat : uint8
{
	PF_Unknown                               = 0,
	PF_A32B32G32R32F                         = 1,
	PF_B8G8R8A8                              = 2,
	PF_G8                                    = 3,
	PF_G16                                   = 4,
	PF_DXT1                                  = 5,
	PF_DXT3                                  = 6,
	PF_DXT5                                  = 7,
	PF_UYVY                                  = 8,
	PF_FloatRGB                              = 9,
	PF_FloatRGBA                             = 10,
	PF_DepthStencil                          = 11,
	PF_ShadowDepth                           = 12,
	PF_R32_FLOAT                             = 13,
	PF_G16R16                                = 14,
	PF_G16R16F                               = 15,
	PF_G16R16F_FILTER                        = 16,
	PF_G32R32F                               = 17,
	PF_A2B10G10R10                           = 18,
	PF_A16B16G16R16                          = 19,
	PF_D24                                   = 20,
	PF_R16F                                  = 21,
	PF_R16F_FILTER                           = 22,
	PF_BC5                                   = 23,
	PF_V8U8                                  = 24,
	PF_A1                                    = 25,
	PF_FloatR11G11B10                        = 26,
	PF_A8                                    = 27,
	PF_R32_UINT                              = 28,
	PF_R32_SINT                              = 29,
	PF_PVRTC2                                = 30,
	PF_PVRTC4                                = 31,
	PF_R16_UINT                              = 32,
	PF_R16_SINT                              = 33,
	PF_R16G16B16A16_UINT                     = 34,
	PF_R16G16B16A16_SINT                     = 35,
	PF_R5G6B5_UNORM                          = 36,
	PF_R8G8B8A8                              = 37,
	PF_A8R8G8B8                              = 38,
	PF_BC4                                   = 39,
	PF_R8G8                                  = 40,
	PF_ATC_RGB                               = 41,
	PF_ATC_RGBA_E                            = 42,
	PF_ATC_RGBA_I                            = 43,
	PF_X24_G8                                = 44,
	PF_ETC1                                  = 45,
	PF_ETC2_RGB                              = 46,
	PF_ETC2_RGBA                             = 47,
	PF_R32G32B32A32_UINT                     = 48,
	PF_R16G16_UINT                           = 49,
	PF_ASTC_4x4                              = 50,
	PF_ASTC_5x5                              = 70,
	PF_ASTC_6x6                              = 51,
	PF_ASTC_8x8                              = 52,
	PF_ASTC_10x10                            = 53,
	PF_ASTC_12x12                            = 54,
	PF_BC6H                                  = 55,
	PF_BC7                                   = 56,
	PF_R8_UINT                               = 57,
	PF_L8                                    = 58,
	PF_XGXR8                                 = 59,
	PF_R8G8B8A8_UINT                         = 60,
	PF_R8G8B8A8_SNORM                        = 61,
	PF_R16G16B16A16_UNORM                    = 62,
	PF_R16G16B16A16_SNORM                    = 63,
	PF_PLATFORM_HDR_0                        = 64,
	PF_PLATFORM_HDR_1                        = 65,
	PF_PLATFORM_HDR_2                        = 66,
	PF_NV12                                  = 67,
	PF_R32G32_UINT                           = 68,
	PF_ASTC_5x4                              = 69,
	PF_ASTC_5x5_0                            = 70,
	PF_ASTC_6x5                              = 71,
	PF_ASTC_8x5                              = 72,
	PF_ASTC_8x6                              = 73,
	PF_ASTC_10x5                             = 74,
	PF_ASTC_10x6                             = 75,
	PF_ASTC_10x8                             = 76,
	PF_ASTC_12x10                            = 77,
	PF_MAX_0                                 = 79,
};

// Enum CoreUObject.ELifetimeCondition
// NumValues: 0x0013
enum class ELifetimeCondition : uint8
{
	COND_None                                = 0,
	COND_InitialOnly                         = 1,
	COND_OwnerOnly                           = 2,
	COND_SkipOwner                           = 3,
	COND_SimulatedOnly                       = 4,
	COND_AutonomousOnly                      = 5,
	COND_SimulatedOrPhysics                  = 6,
	COND_InitialOrOwner                      = 7,
	COND_Custom                              = 8,
	COND_ReplayOrOwner                       = 9,
	COND_ReplayOnly                          = 10,
	COND_SimulatedOnlyNoReplay               = 11,
	COND_SimulatedOrPhysicsNoReplay          = 12,
	COND_SkipReplay                          = 13,
	COND_InitialOrSkipOwner                  = 14,
	COND_OwnerOrFocusTarget                  = 15,
	COND_FocusTargetSkipOwner                = 16,
	COND_Never                               = 31,
	COND_Max                                 = 32,
};

// Enum CoreUObject.EDataValidationResult
// NumValues: 0x0004
enum class EDataValidationResult : uint8
{
	Invalid                                  = 0,
	Valid                                    = 1,
	NotValidated                             = 2,
	EDataValidationResult_MAX                = 3,
};

// Enum CoreUObject.EPropertyAccessChangeNotifyMode
// NumValues: 0x0004
enum class EPropertyAccessChangeNotifyMode : uint8
{
	Default                                  = 0,
	Never                                    = 1,
	Always                                   = 2,
	EPropertyAccessChangeNotifyMode_MAX      = 3,
};

// Enum CoreUObject.EUnit
// NumValues: 0x0033
enum class EUnit : uint8
{
	Micrometers                              = 0,
	Millimeters                              = 1,
	Centimeters                              = 2,
	Meters                                   = 3,
	Kilometers                               = 4,
	Inches                                   = 5,
	Feet                                     = 6,
	Yards                                    = 7,
	Miles                                    = 8,
	Lightyears                               = 9,
	Degrees                                  = 10,
	Radians                                  = 11,
	MetersPerSecond                          = 12,
	KilometersPerHour                        = 13,
	MilesPerHour                             = 14,
	Celsius                                  = 15,
	Farenheit                                = 16,
	Kelvin                                   = 17,
	Micrograms                               = 18,
	Milligrams                               = 19,
	Grams                                    = 20,
	Kilograms                                = 21,
	MetricTons                               = 22,
	Ounces                                   = 23,
	Pounds                                   = 24,
	Stones                                   = 25,
	Newtons                                  = 26,
	PoundsForce                              = 27,
	KilogramsForce                           = 28,
	Hertz                                    = 29,
	Kilohertz                                = 30,
	Megahertz                                = 31,
	Gigahertz                                = 32,
	RevolutionsPerMinute                     = 33,
	Bytes                                    = 34,
	Kilobytes                                = 35,
	Megabytes                                = 36,
	Gigabytes                                = 37,
	Terabytes                                = 38,
	Lumens                                   = 39,
	Milliseconds                             = 43,
	Seconds                                  = 44,
	Minutes                                  = 45,
	Hours                                    = 46,
	Days                                     = 47,
	Months                                   = 48,
	Years                                    = 49,
	Multiplier                               = 52,
	Percentage                               = 51,
	Unspecified                              = 53,
	EUnit_MAX                                = 54,
};

// Enum CoreUObject.EAxis
// NumValues: 0x0005
enum class EAxis : uint8
{
	None                                     = 0,
	X                                        = 1,
	Y                                        = 2,
	Z                                        = 3,
	EAxis_MAX                                = 4,
};

// Enum CoreUObject.ELogTimes
// NumValues: 0x0005
enum class ELogTimes : uint8
{
	None                                     = 0,
	UTC                                      = 1,
	SinceGStartTime                          = 2,
	Local                                    = 3,
	ELogTimes_MAX                            = 4,
};

// Enum CoreUObject.ESearchDir
// NumValues: 0x0003
enum class ESearchDir : uint8
{
	FromStart                                = 0,
	FromEnd                                  = 1,
	ESearchDir_MAX                           = 2,
};

// Enum CoreUObject.ESearchCase
// NumValues: 0x0003
enum class ESearchCase : uint8
{
	CaseSensitive                            = 0,
	IgnoreCase                               = 1,
	ESearchCase_MAX                          = 2,
};

// ScriptStruct CoreUObject.JoinabilitySettings
// 0x0014 (0x0014 - 0x0000)
struct alignas(0x04) FJoinabilitySettings final
{
public:
	uint8                                         Pad_0[0x14];                                       // 0x0000(0x0014)(Fixing Struct Size After Last Property [ Dumper-7 ])
};
static_assert(alignof(FJoinabilitySettings) == 0x000004, "Wrong alignment on FJoinabilitySettings");
static_assert(sizeof(FJoinabilitySettings) == 0x000014, "Wrong size on FJoinabilitySettings");

// ScriptStruct CoreUObject.UniqueNetIdWrapper
// 0x0001 (0x0001 - 0x0000)
struct FUniqueNetIdWrapper
{
public:
	uint8                                         Pad_0[0x1];                                        // 0x0000(0x0001)(Fixing Struct Size After Last Property [ Dumper-7 ])
};
static_assert(alignof(FUniqueNetIdWrapper) == 0x000001, "Wrong alignment on FUniqueNetIdWrapper");
static_assert(sizeof(FUniqueNetIdWrapper) == 0x000001, "Wrong size on FUniqueNetIdWrapper");

// ScriptStruct CoreUObject.FloatRangeBound
// 0x0008 (0x0008 - 0x0000)
struct alignas(0x04) FFloatRangeBound final
{
public:
	uint8                                         Pad_0[0x8];                                        // 0x0000(0x0008)(Fixing Struct Size After Last Property [ Dumper-7 ])
};
static_assert(alignof(FFloatRangeBound) == 0x000004, "Wrong alignment on FFloatRangeBound");
static_assert(sizeof(FFloatRangeBound) == 0x000008, "Wrong size on FFloatRangeBound");

// ScriptStruct CoreUObject.Guid
// 0x0010 (0x0010 - 0x0000)
struct alignas(0x04) FGuid final
{
public:
	uint8                                         Pad_0[0x10];                                       // 0x0000(0x0010)(Fixing Struct Size After Last Property [ Dumper-7 ])
};
static_assert(alignof(FGuid) == 0x000004, "Wrong alignment on FGuid");
static_assert(sizeof(FGuid) == 0x000010, "Wrong size on FGuid");

struct FHitResult
{
	uint8 padding[0x88]; // 136 字节，占位用
};


// ScriptStruct CoreUObject.Vector
// 0x000C (0x000C - 0x0000)
struct alignas(0x04) FVector
{
public:
	using UnderlayingType = float;

	float                                         X;
	float                                         Y;
	float                                         Z;


public:
	FVector& Normalize()
	{
		*this /= Magnitude();
		return *this;
	}
	FVector& operator*=(const FVector& Other)
	{
		*this = *this * Other;
		return *this;
	}
	FVector& operator*=(float Scalar)
	{
		*this = *this * Scalar;
		return *this;
	}
	FVector& operator+=(const FVector& Other)
	{
		*this = *this + Other;
		return *this;
	}
	FVector& operator-=(const FVector& Other)
	{
		*this = *this - Other;
		return *this;
	}
	FVector& operator/=(const FVector& Other)
	{
		*this = *this / Other;
		return *this;
	}
	FVector& operator/=(float Scalar)
	{
		*this = *this / Scalar;
		return *this;
	}

	UnderlayingType Dot(const FVector& Other) const
	{
		return (X * Other.X) + (Y * Other.Y) + (Z * Other.Z);
	}
	UnderlayingType GetDistanceTo(const FVector& Other) const
	{
		FVector DiffVector = Other - *this;
		return DiffVector.Magnitude();
	}
	UnderlayingType GetDistanceToInMeters(const FVector& Other) const
	{
		return GetDistanceTo(Other) * static_cast<UnderlayingType>(0.01);
	}
	FVector GetNormalized() const
	{
		return *this / Magnitude();
	}
	bool IsZero() const
	{
		return X == 0.0 && Y == 0.0 && Z == 0.0;
	}
	UnderlayingType Magnitude() const
	{
		return std::sqrt((X * X) + (Y * Y) + (Z * Z));
	}
	bool operator!=(const FVector& Other) const
	{
		return X != Other.X || Y != Other.Y || Z != Other.Z;
	}
	FVector operator*(const FVector& Other) const
	{
		return { X * Other.X, Y * Other.Y, Z * Other.Z };
	}
	FVector operator*(float Scalar) const
	{
		return { X * Scalar, Y * Scalar, Z * Scalar };
	}
	FVector operator+(const FVector& Other) const
	{
		return { X + Other.X, Y + Other.Y, Z + Other.Z };
	}
	FVector operator-(const FVector& Other) const
	{
		return { X - Other.X, Y - Other.Y, Z - Other.Z };
	}
	FVector operator/(const FVector& Other) const
	{
		if (Other.X == 0.0f || Other.Y == 0.0f || Other.Z == 0.0f)
			return *this;

		return { X / Other.X, Y / Other.Y, Z / Other.Z };
	}
	FVector operator/(float Scalar) const
	{
		if (Scalar == 0.0f)
			return *this;

		return { X / Scalar, Y / Scalar, Z / Scalar };
	}
	bool operator==(const FVector& Other) const
	{
		return X == Other.X && Y == Other.Y && Z == Other.Z;
	}
};
static_assert(alignof(FVector) == 0x000004, "Wrong alignment on FVector");
static_assert(sizeof(FVector) == 0x00000C, "Wrong size on FVector");

// ScriptStruct CoreUObject.Vector4
// 0x0010 (0x0010 - 0x0000)
struct alignas(0x10) FVector4 final
{
public:
	uint8                                         Pad_0[0x10];                                       // 0x0000(0x0010)(Fixing Struct Size After Last Property [ Dumper-7 ])
};
static_assert(alignof(FVector4) == 0x000010, "Wrong alignment on FVector4");
static_assert(sizeof(FVector4) == 0x000010, "Wrong size on FVector4");

// ScriptStruct CoreUObject.Vector2D
// 0x0008 (0x0008 - 0x0000)
struct alignas(0x04) FVector2D final
{
public:
	using UnderlayingType = float;
	float                                         X;                                                 // 0x0000(0x0004)(Edit, BlueprintVisible, ZeroConstructor, SaveGame, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	float                                         Y;                                                 // 0x0004(0x0004)(Edit, BlueprintVisible, ZeroConstructor, SaveGame, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

public:
	FVector2D& Normalize()
	{
		*this /= Magnitude();
		return *this;
	}
	FVector2D& operator*=(const FVector2D& Other)
	{
		*this = *this * Other;
		return *this;
	}
	FVector2D& operator*=(float Scalar)
	{
		*this = *this * Scalar;
		return *this;
	}
	FVector2D& operator+=(const FVector2D& Other)
	{
		*this = *this + Other;
		return *this;
	}
	FVector2D& operator-=(const FVector2D& Other)
	{
		*this = *this - Other;
		return *this;
	}
	FVector2D& operator/=(const FVector2D& Other)
	{
		*this = *this / Other;
		return *this;
	}
	FVector2D& operator/=(float Scalar)
	{
		*this = *this / Scalar;
		return *this;
	}

	UnderlayingType Dot(const FVector2D& Other) const
	{
		return (X * Other.X) + (Y * Other.Y);
	}
	UnderlayingType GetDistanceTo(const FVector2D& Other) const
	{
		FVector2D DiffVector = Other - *this;
		return DiffVector.Magnitude();
	}
	FVector2D GetNormalized() const
	{
		return *this / Magnitude();
	}
	bool IsZero() const
	{
		return X == 0.0 && Y == 0.0;
	}
	UnderlayingType Magnitude() const
	{
		return std::sqrt((X * X) + (Y * Y));
	}
	bool operator!=(const FVector2D& Other) const
	{
		return X != Other.X || Y != Other.Y;
	}
	FVector2D operator*(const FVector2D& Other) const
	{
		return { X * Other.X, Y * Other.Y };
	}
	FVector2D operator*(float Scalar) const
	{
		return { X * Scalar, Y * Scalar };
	}
	FVector2D operator+(const FVector2D& Other) const
	{
		return { X + Other.X, Y + Other.Y };
	}
	FVector2D operator-(const FVector2D& Other) const
	{
		return { X - Other.X, Y - Other.Y };
	}
	FVector2D operator/(const FVector2D& Other) const
	{
		if (Other.X == 0.0f || Other.Y == 0.0f)
			return *this;

		return { X / Other.X, Y / Other.Y };
	}
	FVector2D operator/(float Scalar) const
	{
		if (Scalar == 0.0f)
			return *this;

		return { X / Scalar, Y / Scalar };
	}
	bool operator==(const FVector2D& Other) const
	{
		return X == Other.X && Y == Other.Y;
	}
};
static_assert(alignof(FVector2D) == 0x000004, "Wrong alignment on FVector2D");
static_assert(sizeof(FVector2D) == 0x000008, "Wrong size on FVector2D");

// ScriptStruct CoreUObject.Int32Range
// 0x0010 (0x0010 - 0x0000)
struct alignas(0x04) FInt32Range final
{
public:
	uint8                                         Pad_0[0x10];                                       // 0x0000(0x0010)(Fixing Struct Size After Last Property [ Dumper-7 ])
};
static_assert(alignof(FInt32Range) == 0x000004, "Wrong alignment on FInt32Range");
static_assert(sizeof(FInt32Range) == 0x000010, "Wrong size on FInt32Range");

// ScriptStruct CoreUObject.TwoVectors
// 0x0018 (0x0018 - 0x0000)
struct alignas(0x04) FTwoVectors final
{
public:
	uint8                                         Pad_0[0x18];                                       // 0x0000(0x0018)(Fixing Struct Size After Last Property [ Dumper-7 ])
};
static_assert(alignof(FTwoVectors) == 0x000004, "Wrong alignment on FTwoVectors");
static_assert(sizeof(FTwoVectors) == 0x000018, "Wrong size on FTwoVectors");

// ScriptStruct CoreUObject.AutomationExecutionEntry
// 0x0058 (0x0058 - 0x0000)
struct alignas(0x08) FAutomationExecutionEntry final
{
public:
	uint8                                         Pad_0[0x58];                                       // 0x0000(0x0058)(Fixing Struct Size After Last Property [ Dumper-7 ])
};
static_assert(alignof(FAutomationExecutionEntry) == 0x000008, "Wrong alignment on FAutomationExecutionEntry");
static_assert(sizeof(FAutomationExecutionEntry) == 0x000058, "Wrong size on FAutomationExecutionEntry");

// ScriptStruct CoreUObject.Plane
// 0x0004 (0x0010 - 0x000C)
struct alignas(0x10) FPlane final : public FVector
{
};
static_assert(alignof(FPlane) == 0x000010, "Wrong alignment on FPlane");
static_assert(sizeof(FPlane) == 0x000010, "Wrong size on FPlane");

// ScriptStruct CoreUObject.Rotator
// 0x000C (0x000C - 0x0000)
struct FRotator
{
	float                                         Pitch;                                                        // 0x0000(0x0004)
	float                                         Yaw;                                                          // 0x0004(0x0004)
	float                                         Roll;                                                         // 0x0008(0x0004)
};
static_assert(alignof(FRotator) == 0x000004, "Wrong alignment on FRotator");
static_assert(sizeof(FRotator) == 0x00000C, "Wrong size on FRotator");

// ScriptStruct CoreUObject.Quat
// 0x0010 (0x0010 - 0x0000)
struct alignas(0x10) FQuat final
{
public:
	uint8                                         Pad_0[0x10];                                       // 0x0000(0x0010)(Fixing Struct Size After Last Property [ Dumper-7 ])
};
static_assert(alignof(FQuat) == 0x000010, "Wrong alignment on FQuat");
static_assert(sizeof(FQuat) == 0x000010, "Wrong size on FQuat");

// ScriptStruct CoreUObject.PackedNormal
// 0x0004 (0x0004 - 0x0000)
struct FPackedNormal final
{
public:
	uint8                                         Pad_0[0x4];                                        // 0x0000(0x0004)(Fixing Struct Size After Last Property [ Dumper-7 ])
};
static_assert(alignof(FPackedNormal) == 0x000001, "Wrong alignment on FPackedNormal");
static_assert(sizeof(FPackedNormal) == 0x000004, "Wrong size on FPackedNormal");

// ScriptStruct CoreUObject.PackedRGB10A2N
// 0x0004 (0x0004 - 0x0000)
struct alignas(0x04) FPackedRGB10A2N final
{
public:
	uint8                                         Pad_0[0x4];                                        // 0x0000(0x0004)(Fixing Struct Size After Last Property [ Dumper-7 ])
};
static_assert(alignof(FPackedRGB10A2N) == 0x000004, "Wrong alignment on FPackedRGB10A2N");
static_assert(sizeof(FPackedRGB10A2N) == 0x000004, "Wrong size on FPackedRGB10A2N");

// ScriptStruct CoreUObject.PackedRGBA16N
// 0x0008 (0x0008 - 0x0000)
struct alignas(0x04) FPackedRGBA16N final
{
public:
	uint8                                         Pad_0[0x8];                                        // 0x0000(0x0008)(Fixing Struct Size After Last Property [ Dumper-7 ])
};
static_assert(alignof(FPackedRGBA16N) == 0x000004, "Wrong alignment on FPackedRGBA16N");
static_assert(sizeof(FPackedRGBA16N) == 0x000008, "Wrong size on FPackedRGBA16N");

// ScriptStruct CoreUObject.IntPoint
// 0x0008 (0x0008 - 0x0000)
struct alignas(0x04) FIntPoint final
{
public:
	uint8                                         Pad_0[0x8];                                        // 0x0000(0x0008)(Fixing Struct Size After Last Property [ Dumper-7 ])
};
static_assert(alignof(FIntPoint) == 0x000004, "Wrong alignment on FIntPoint");
static_assert(sizeof(FIntPoint) == 0x000008, "Wrong size on FIntPoint");

// ScriptStruct CoreUObject.Ray
// 0x0018 (0x0018 - 0x0000)
struct alignas(0x04) FRay final
{
public:
	uint8                                         Pad_0[0x18];                                       // 0x0000(0x0018)(Fixing Struct Size After Last Property [ Dumper-7 ])
};
static_assert(alignof(FRay) == 0x000004, "Wrong alignment on FRay");
static_assert(sizeof(FRay) == 0x000018, "Wrong size on FRay");

// ScriptStruct CoreUObject.IntVector
// 0x000C (0x000C - 0x0000)
struct alignas(0x04) FIntVector final
{
public:
	uint8                                         Pad_0[0xC];                                        // 0x0000(0x000C)(Fixing Struct Size After Last Property [ Dumper-7 ])
};
static_assert(alignof(FIntVector) == 0x000004, "Wrong alignment on FIntVector");
static_assert(sizeof(FIntVector) == 0x00000C, "Wrong size on FIntVector");

// ScriptStruct CoreUObject.Color
// 0x0004 (0x0004 - 0x0000)
struct alignas(0x04) FColor final
{
public:
	uint8                                         Pad_0[0x4];                                        // 0x0000(0x0004)(Fixing Struct Size After Last Property [ Dumper-7 ])
};
static_assert(alignof(FColor) == 0x000004, "Wrong alignment on FColor");
static_assert(sizeof(FColor) == 0x000004, "Wrong size on FColor");

// ScriptStruct CoreUObject.LinearColor
// 0x0010 (0x0010 - 0x0000)
struct alignas(0x04) FLinearColor final
{
public:
	uint8                                         Pad_0[0x10];                                       // 0x0000(0x0010)(Fixing Struct Size After Last Property [ Dumper-7 ])
};
static_assert(alignof(FLinearColor) == 0x000004, "Wrong alignment on FLinearColor");
static_assert(sizeof(FLinearColor) == 0x000010, "Wrong size on FLinearColor");

// ScriptStruct CoreUObject.Box
// 0x001C (0x001C - 0x0000)
struct alignas(0x04) FBox final
{
public:
	uint8                                         Pad_0[0x1C];                                       // 0x0000(0x001C)(Fixing Struct Size After Last Property [ Dumper-7 ])
};
static_assert(alignof(FBox) == 0x000004, "Wrong alignment on FBox");
static_assert(sizeof(FBox) == 0x00001C, "Wrong size on FBox");

// ScriptStruct CoreUObject.Box2D
// 0x0014 (0x0014 - 0x0000)
struct alignas(0x04) FBox2D final
{
public:
	uint8                                         Pad_0[0x14];                                       // 0x0000(0x0014)(Fixing Struct Size After Last Property [ Dumper-7 ])
};
static_assert(alignof(FBox2D) == 0x000004, "Wrong alignment on FBox2D");
static_assert(sizeof(FBox2D) == 0x000014, "Wrong size on FBox2D");

// ScriptStruct CoreUObject.BoxSphereBounds
// 0x001C (0x001C - 0x0000)
struct alignas(0x04) FBoxSphereBounds final
{
public:
	uint8                                         Pad_0[0x1C];                                       // 0x0000(0x001C)(Fixing Struct Size After Last Property [ Dumper-7 ])
};
static_assert(alignof(FBoxSphereBounds) == 0x000004, "Wrong alignment on FBoxSphereBounds");
static_assert(sizeof(FBoxSphereBounds) == 0x00001C, "Wrong size on FBoxSphereBounds");

// ScriptStruct CoreUObject.OrientedBox
// 0x003C (0x003C - 0x0000)
struct alignas(0x04) FOrientedBox final
{
public:
	uint8                                         Pad_0[0x3C];                                       // 0x0000(0x003C)(Fixing Struct Size After Last Property [ Dumper-7 ])
};
static_assert(alignof(FOrientedBox) == 0x000004, "Wrong alignment on FOrientedBox");
static_assert(sizeof(FOrientedBox) == 0x00003C, "Wrong size on FOrientedBox");

// ScriptStruct CoreUObject.Matrix
// 0x0040 (0x0040 - 0x0000)
struct alignas(0x10) FMatrix final
{
public:
	uint8                                         Pad_0[0x40];                                       // 0x0000(0x0040)(Fixing Struct Size After Last Property [ Dumper-7 ])
};
static_assert(alignof(FMatrix) == 0x000010, "Wrong alignment on FMatrix");
static_assert(sizeof(FMatrix) == 0x000040, "Wrong size on FMatrix");

// ScriptStruct CoreUObject.InterpCurvePointFloat
// 0x0014 (0x0014 - 0x0000)
struct alignas(0x04) FInterpCurvePointFloat final
{
public:
	uint8                                         Pad_0[0x14];                                       // 0x0000(0x0014)(Fixing Struct Size After Last Property [ Dumper-7 ])
};
static_assert(alignof(FInterpCurvePointFloat) == 0x000004, "Wrong alignment on FInterpCurvePointFloat");
static_assert(sizeof(FInterpCurvePointFloat) == 0x000014, "Wrong size on FInterpCurvePointFloat");

// ScriptStruct CoreUObject.InterpCurveFloat
// 0x0018 (0x0018 - 0x0000)
struct alignas(0x08) FInterpCurveFloat final
{
public:
	uint8                                         Pad_0[0x18];                                       // 0x0000(0x0018)(Fixing Struct Size After Last Property [ Dumper-7 ])
};
static_assert(alignof(FInterpCurveFloat) == 0x000008, "Wrong alignment on FInterpCurveFloat");
static_assert(sizeof(FInterpCurveFloat) == 0x000018, "Wrong size on FInterpCurveFloat");

// ScriptStruct CoreUObject.InterpCurvePointVector2D
// 0x0020 (0x0020 - 0x0000)
struct alignas(0x04) FInterpCurvePointVector2D final
{
public:
	uint8                                         Pad_0[0x20];                                       // 0x0000(0x0020)(Fixing Struct Size After Last Property [ Dumper-7 ])
};
static_assert(alignof(FInterpCurvePointVector2D) == 0x000004, "Wrong alignment on FInterpCurvePointVector2D");
static_assert(sizeof(FInterpCurvePointVector2D) == 0x000020, "Wrong size on FInterpCurvePointVector2D");

// ScriptStruct CoreUObject.InterpCurveVector2D
// 0x0018 (0x0018 - 0x0000)
struct alignas(0x08) FInterpCurveVector2D final
{
public:
	uint8                                         Pad_0[0x18];                                       // 0x0000(0x0018)(Fixing Struct Size After Last Property [ Dumper-7 ])
};
static_assert(alignof(FInterpCurveVector2D) == 0x000008, "Wrong alignment on FInterpCurveVector2D");
static_assert(sizeof(FInterpCurveVector2D) == 0x000018, "Wrong size on FInterpCurveVector2D");

// ScriptStruct CoreUObject.InterpCurvePointVector
// 0x002C (0x002C - 0x0000)
struct alignas(0x04) FInterpCurvePointVector final
{
public:
	uint8                                         Pad_0[0x2C];                                       // 0x0000(0x002C)(Fixing Struct Size After Last Property [ Dumper-7 ])
};
static_assert(alignof(FInterpCurvePointVector) == 0x000004, "Wrong alignment on FInterpCurvePointVector");
static_assert(sizeof(FInterpCurvePointVector) == 0x00002C, "Wrong size on FInterpCurvePointVector");

// ScriptStruct CoreUObject.InterpCurveVector
// 0x0018 (0x0018 - 0x0000)
struct alignas(0x08) FInterpCurveVector final
{
public:
	uint8                                         Pad_0[0x18];                                       // 0x0000(0x0018)(Fixing Struct Size After Last Property [ Dumper-7 ])
};
static_assert(alignof(FInterpCurveVector) == 0x000008, "Wrong alignment on FInterpCurveVector");
static_assert(sizeof(FInterpCurveVector) == 0x000018, "Wrong size on FInterpCurveVector");

// ScriptStruct CoreUObject.InterpCurvePointQuat
// 0x0050 (0x0050 - 0x0000)
struct alignas(0x10) FInterpCurvePointQuat final
{
public:
	uint8                                         Pad_0[0x50];                                       // 0x0000(0x0050)(Fixing Struct Size After Last Property [ Dumper-7 ])
};
static_assert(alignof(FInterpCurvePointQuat) == 0x000010, "Wrong alignment on FInterpCurvePointQuat");
static_assert(sizeof(FInterpCurvePointQuat) == 0x000050, "Wrong size on FInterpCurvePointQuat");

// ScriptStruct CoreUObject.InterpCurveQuat
// 0x0018 (0x0018 - 0x0000)
struct alignas(0x08) FInterpCurveQuat final
{
public:
	uint8                                         Pad_0[0x18];                                       // 0x0000(0x0018)(Fixing Struct Size After Last Property [ Dumper-7 ])
};
static_assert(alignof(FInterpCurveQuat) == 0x000008, "Wrong alignment on FInterpCurveQuat");
static_assert(sizeof(FInterpCurveQuat) == 0x000018, "Wrong size on FInterpCurveQuat");

// ScriptStruct CoreUObject.InterpCurvePointTwoVectors
// 0x0050 (0x0050 - 0x0000)
struct alignas(0x04) FInterpCurvePointTwoVectors final
{
public:
	uint8                                         Pad_0[0x50];                                       // 0x0000(0x0050)(Fixing Struct Size After Last Property [ Dumper-7 ])
};
static_assert(alignof(FInterpCurvePointTwoVectors) == 0x000004, "Wrong alignment on FInterpCurvePointTwoVectors");
static_assert(sizeof(FInterpCurvePointTwoVectors) == 0x000050, "Wrong size on FInterpCurvePointTwoVectors");

// ScriptStruct CoreUObject.InterpCurveTwoVectors
// 0x0018 (0x0018 - 0x0000)
struct alignas(0x08) FInterpCurveTwoVectors final
{
public:
	uint8                                         Pad_0[0x18];                                       // 0x0000(0x0018)(Fixing Struct Size After Last Property [ Dumper-7 ])
};
static_assert(alignof(FInterpCurveTwoVectors) == 0x000008, "Wrong alignment on FInterpCurveTwoVectors");
static_assert(sizeof(FInterpCurveTwoVectors) == 0x000018, "Wrong size on FInterpCurveTwoVectors");

// ScriptStruct CoreUObject.InterpCurvePointLinearColor
// 0x0038 (0x0038 - 0x0000)
struct alignas(0x04) FInterpCurvePointLinearColor final
{
public:
	uint8                                         Pad_0[0x38];                                       // 0x0000(0x0038)(Fixing Struct Size After Last Property [ Dumper-7 ])
};
static_assert(alignof(FInterpCurvePointLinearColor) == 0x000004, "Wrong alignment on FInterpCurvePointLinearColor");
static_assert(sizeof(FInterpCurvePointLinearColor) == 0x000038, "Wrong size on FInterpCurvePointLinearColor");

// ScriptStruct CoreUObject.InterpCurveLinearColor
// 0x0018 (0x0018 - 0x0000)
struct alignas(0x08) FInterpCurveLinearColor final
{
public:
	uint8                                         Pad_0[0x18];                                       // 0x0000(0x0018)(Fixing Struct Size After Last Property [ Dumper-7 ])
};
static_assert(alignof(FInterpCurveLinearColor) == 0x000008, "Wrong alignment on FInterpCurveLinearColor");
static_assert(sizeof(FInterpCurveLinearColor) == 0x000018, "Wrong size on FInterpCurveLinearColor");

// ScriptStruct CoreUObject.Transform
// 0x0030 (0x0030 - 0x0000)
struct alignas(0x10) FTransform final
{
public:
	uint8                                         Pad_0[0x30];                                       // 0x0000(0x0030)(Fixing Struct Size After Last Property [ Dumper-7 ])
};
static_assert(alignof(FTransform) == 0x000010, "Wrong alignment on FTransform");
static_assert(sizeof(FTransform) == 0x000030, "Wrong size on FTransform");

// ScriptStruct CoreUObject.RandomStream
// 0x0008 (0x0008 - 0x0000)
struct alignas(0x04) FRandomStream final
{
public:
	uint8                                         Pad_0[0x8];                                        // 0x0000(0x0008)(Fixing Struct Size After Last Property [ Dumper-7 ])
};
static_assert(alignof(FRandomStream) == 0x000004, "Wrong alignment on FRandomStream");
static_assert(sizeof(FRandomStream) == 0x000008, "Wrong size on FRandomStream");

// ScriptStruct CoreUObject.FloatInterval
// 0x0008 (0x0008 - 0x0000)
struct alignas(0x04) FFloatInterval final
{
public:
	uint8                                         Pad_0[0x8];                                        // 0x0000(0x0008)(Fixing Struct Size After Last Property [ Dumper-7 ])
};
static_assert(alignof(FFloatInterval) == 0x000004, "Wrong alignment on FFloatInterval");
static_assert(sizeof(FFloatInterval) == 0x000008, "Wrong size on FFloatInterval");

// ScriptStruct CoreUObject.DateTime
// 0x0008 (0x0008 - 0x0000)
struct alignas(0x08) FDateTime final
{
public:
	uint8                                         Pad_0[0x8];                                        // 0x0000(0x0008)(Fixing Struct Size After Last Property [ Dumper-7 ])
};
static_assert(alignof(FDateTime) == 0x000008, "Wrong alignment on FDateTime");
static_assert(sizeof(FDateTime) == 0x000008, "Wrong size on FDateTime");

// ScriptStruct CoreUObject.FrameNumber
// 0x0004 (0x0004 - 0x0000)
struct alignas(0x04) FFrameNumber final
{
public:
	uint8                                         Pad_0[0x4];                                        // 0x0000(0x0004)(Fixing Struct Size After Last Property [ Dumper-7 ])
};
static_assert(alignof(FFrameNumber) == 0x000004, "Wrong alignment on FFrameNumber");
static_assert(sizeof(FFrameNumber) == 0x000004, "Wrong size on FFrameNumber");

// ScriptStruct CoreUObject.FrameRate
// 0x0008 (0x0008 - 0x0000)
struct alignas(0x04) FFrameRate final
{
public:
	uint8                                         Pad_0[0x8];                                        // 0x0000(0x0008)(Fixing Struct Size After Last Property [ Dumper-7 ])
};
static_assert(alignof(FFrameRate) == 0x000004, "Wrong alignment on FFrameRate");
static_assert(sizeof(FFrameRate) == 0x000008, "Wrong size on FFrameRate");

// ScriptStruct CoreUObject.FrameTime
// 0x0008 (0x0008 - 0x0000)
struct alignas(0x04) FFrameTime final
{
public:
	uint8                                         Pad_0[0x8];                                        // 0x0000(0x0008)(Fixing Struct Size After Last Property [ Dumper-7 ])
};
static_assert(alignof(FFrameTime) == 0x000004, "Wrong alignment on FFrameTime");
static_assert(sizeof(FFrameTime) == 0x000008, "Wrong size on FFrameTime");

// ScriptStruct CoreUObject.AutomationEvent
// 0x0038 (0x0038 - 0x0000)
struct alignas(0x08) FAutomationEvent final
{
public:
	uint8                                         Pad_0[0x38];                                       // 0x0000(0x0038)(Fixing Struct Size After Last Property [ Dumper-7 ])
};
static_assert(alignof(FAutomationEvent) == 0x000008, "Wrong alignment on FAutomationEvent");
static_assert(sizeof(FAutomationEvent) == 0x000038, "Wrong size on FAutomationEvent");

// ScriptStruct CoreUObject.QualifiedFrameTime
// 0x0010 (0x0010 - 0x0000)
struct alignas(0x04) FQualifiedFrameTime final
{
public:
	uint8                                         Pad_0[0x10];                                       // 0x0000(0x0010)(Fixing Struct Size After Last Property [ Dumper-7 ])
};
static_assert(alignof(FQualifiedFrameTime) == 0x000004, "Wrong alignment on FQualifiedFrameTime");
static_assert(sizeof(FQualifiedFrameTime) == 0x000010, "Wrong size on FQualifiedFrameTime");

// ScriptStruct CoreUObject.Timecode
// 0x0014 (0x0014 - 0x0000)
struct alignas(0x04) FTimecode final
{
public:
	uint8                                         Pad_0[0x14];                                       // 0x0000(0x0014)(Fixing Struct Size After Last Property [ Dumper-7 ])
};
static_assert(alignof(FTimecode) == 0x000004, "Wrong alignment on FTimecode");
static_assert(sizeof(FTimecode) == 0x000014, "Wrong size on FTimecode");

// ScriptStruct CoreUObject.Timespan
// 0x0008 (0x0008 - 0x0000)
struct alignas(0x08) FTimespan final
{
public:
	uint8                                         Pad_0[0x8];                                        // 0x0000(0x0008)(Fixing Struct Size After Last Property [ Dumper-7 ])
};
static_assert(alignof(FTimespan) == 0x000008, "Wrong alignment on FTimespan");
static_assert(sizeof(FTimespan) == 0x000008, "Wrong size on FTimespan");

// ScriptStruct CoreUObject.Int32Interval
// 0x0008 (0x0008 - 0x0000)
struct alignas(0x04) FInt32Interval final
{
public:
	uint8                                         Pad_0[0x8];                                        // 0x0000(0x0008)(Fixing Struct Size After Last Property [ Dumper-7 ])
};
static_assert(alignof(FInt32Interval) == 0x000004, "Wrong alignment on FInt32Interval");
static_assert(sizeof(FInt32Interval) == 0x000008, "Wrong size on FInt32Interval");

// ScriptStruct CoreUObject.SoftObjectPath
// 0x0018 (0x0018 - 0x0000)
struct alignas(0x08) FSoftObjectPath
{
public:
	uint8                                         Pad_0[0x18];                                       // 0x0000(0x0018)(Fixing Struct Size After Last Property [ Dumper-7 ])
};
static_assert(alignof(FSoftObjectPath) == 0x000008, "Wrong alignment on FSoftObjectPath");
static_assert(sizeof(FSoftObjectPath) == 0x000018, "Wrong size on FSoftObjectPath");

// ScriptStruct CoreUObject.Sphere
// 0x0010 (0x0010 - 0x0000)
struct alignas(0x04) FSphere final
{
public:
	uint8                                         Pad_0[0x10];                                       // 0x0000(0x0010)(Fixing Struct Size After Last Property [ Dumper-7 ])
};
static_assert(alignof(FSphere) == 0x000004, "Wrong alignment on FSphere");
static_assert(sizeof(FSphere) == 0x000010, "Wrong size on FSphere");

// ScriptStruct CoreUObject.SoftClassPath
// 0x0000 (0x0018 - 0x0018)
struct FSoftClassPath final : public FSoftObjectPath
{
};
static_assert(alignof(FSoftClassPath) == 0x000008, "Wrong alignment on FSoftClassPath");
static_assert(sizeof(FSoftClassPath) == 0x000018, "Wrong size on FSoftClassPath");

// ScriptStruct CoreUObject.PrimaryAssetType
// 0x0008 (0x0008 - 0x0000)
struct alignas(0x04) FPrimaryAssetType final
{
public:
	uint8                                         Pad_0[0x8];                                        // 0x0000(0x0008)(Fixing Struct Size After Last Property [ Dumper-7 ])
};
static_assert(alignof(FPrimaryAssetType) == 0x000004, "Wrong alignment on FPrimaryAssetType");
static_assert(sizeof(FPrimaryAssetType) == 0x000008, "Wrong size on FPrimaryAssetType");

// ScriptStruct CoreUObject.PrimaryAssetId
// 0x0010 (0x0010 - 0x0000)
struct alignas(0x04) FPrimaryAssetId final
{
public:
	uint8                                         Pad_0[0x10];                                       // 0x0000(0x0010)(Fixing Struct Size After Last Property [ Dumper-7 ])
};
static_assert(alignof(FPrimaryAssetId) == 0x000004, "Wrong alignment on FPrimaryAssetId");
static_assert(sizeof(FPrimaryAssetId) == 0x000010, "Wrong size on FPrimaryAssetId");

// ScriptStruct CoreUObject.FallbackStruct
// 0x0001 (0x0001 - 0x0000)
struct FFallbackStruct final
{
public:
	uint8                                         Pad_0[0x1];                                        // 0x0000(0x0001)(Fixing Struct Size After Last Property [ Dumper-7 ])
};
static_assert(alignof(FFallbackStruct) == 0x000001, "Wrong alignment on FFallbackStruct");
static_assert(sizeof(FFallbackStruct) == 0x000001, "Wrong size on FFallbackStruct");

// ScriptStruct CoreUObject.FloatRange
// 0x0010 (0x0010 - 0x0000)
struct alignas(0x04) FFloatRange final
{
public:
	uint8                                         Pad_0[0x10];                                       // 0x0000(0x0010)(Fixing Struct Size After Last Property [ Dumper-7 ])
};
static_assert(alignof(FFloatRange) == 0x000004, "Wrong alignment on FFloatRange");
static_assert(sizeof(FFloatRange) == 0x000010, "Wrong size on FFloatRange");

// ScriptStruct CoreUObject.Int32RangeBound
// 0x0008 (0x0008 - 0x0000)
struct alignas(0x04) FInt32RangeBound final
{
public:
	uint8                                         Pad_0[0x8];                                        // 0x0000(0x0008)(Fixing Struct Size After Last Property [ Dumper-7 ])
};
static_assert(alignof(FInt32RangeBound) == 0x000004, "Wrong alignment on FInt32RangeBound");
static_assert(sizeof(FInt32RangeBound) == 0x000008, "Wrong size on FInt32RangeBound");

// ScriptStruct CoreUObject.PolyglotTextData
// 0x00B8 (0x00B8 - 0x0000)
struct alignas(0x08) FPolyglotTextData final
{
public:
	uint8                                         Pad_0[0xB8];                                       // 0x0000(0x00B8)(Fixing Struct Size After Last Property [ Dumper-7 ])
};
static_assert(alignof(FPolyglotTextData) == 0x000008, "Wrong alignment on FPolyglotTextData");
static_assert(sizeof(FPolyglotTextData) == 0x0000B8, "Wrong size on FPolyglotTextData");

// ScriptStruct CoreUObject.CapsuleShape
// 0x0020 (0x0020 - 0x0000)
struct alignas(0x04) FCapsuleShape final
{
public:
	uint8                                         Pad_0[0x20];                                       // 0x0000(0x0020)(Fixing Struct Size After Last Property [ Dumper-7 ])
};
static_assert(alignof(FCapsuleShape) == 0x000004, "Wrong alignment on FCapsuleShape");
static_assert(sizeof(FCapsuleShape) == 0x000020, "Wrong size on FCapsuleShape");

}

