#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// FORWARD DECLARATIONS


namespace SafeHouse { enum class EIconState : uint8; }

namespace GameplayAbilities { struct FServerAbilityRPCBatch; }

namespace WBP_CommonSubTabLiveS2_0 { class UWBP_CommonSubTabLiveS2_C; }

namespace WBP_CommonTabV1 { class UWBP_CommonTabV1_C; }

namespace WBP_CommonMainTabLiveS2 { class UWBP_CommonMainTabLiveS2_C; }

namespace WBP_CommonSubTabLiveS2 { class UWBP_CommonSubTabLiveS2_C; }

namespace WBP_CommonTabV1_0 { class UWBP_CommonTabV1_C; }

namespace WBP_CommonMainTabLiveS2_0 { class UWBP_CommonMainTabLiveS2_C; }

namespace DFMGlobalDefines { enum class EIconState : uint8; }

